"use client";

import { Box, Button, ChakraProvider, Flex, Image, Input, InputGroup, InputRightElement } from "@chakra-ui/react";
import Sidebar from "../Components/sidebar";
import Container from "../Components/Container/index";
import DrawerExample from "../Components/drawer/index";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <Box>
      <Flex alignItems={{md:"center"}}>
        <Box display={["none", "none", "block", "block", "block"]}>
          <Sidebar />
        </Box>
        <Box>
          <Box
            position="absolute"
            top="0"
            left="0"
            color="white"
            bg="black"
            w="100%"
            p="10px"
            mb={{sm:'4rem'}}
          >
            <Container>
              <Flex justifyContent="space-between" alignItems="center">
                <Box display={["block", "block", "none", "none", "none"]}>
                  <DrawerExample />
                </Box>
                <Box w="150px">
                  <Image src="/mongo-logo.png" boxSize="full" />
                </Box>
                <Box me="20px" display={['none','block','block','block','block']}>
                  <InputGroup size="md" border='none'>
                    <Input
                      pr="4.5rem"
                      type="text"
                      border='none'
                      placeholder="Search"
                    />
                    <InputRightElement width="4.5rem">
                      <Button h="1.75rem" size="sm" colorScheme="linkedin">
                        Search
                      </Button>
                    </InputRightElement>
                  </InputGroup>
                </Box>
              </Flex>
            </Container>
          </Box>
          <Box mt={['4rem','4rem','0','0','0']} ms={{md:"3rem"}}>{children}</Box>
        </Box>
      </Flex>
    </Box>
  );
}
