"use client"

import Head from 'next/head'
import { Box, Flex, Heading } from '@chakra-ui/react'
import SignUp from './Form/SignUp'

export default function Home() {


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <Flex alignItems='center'>
          <Box
            bgImage="url('/mongodb.png')"
            bgPosition="center"
            bgRepeat="no-repeat"
            bgSize='cover'
            h='100vh'
            w='50%'
          >
          </Box>
          <Box w='50%'>
            <SignUp />
          </Box>
        </Flex >
      </Box >
    </>
  )
}
